### ISSUE TITLE
Getting warnings if $this->aliasMap['classNameToAliasMapping'][$originalClassName] is not iterable

### ISSUE THREAD

**Issue by sabbelasichon** [TYPO3/class-alias-loader#21]
When i am running typo3-rector with highest error level i am getting warnings with message "Warning: Invalid argument supplied for foreach() in ClassAliasLoader.php on line 186". 

I cannot tell what´s the root of the problem or why stepping into the foreach anyways. But maybe it is safe to check if $this->aliasMap['classNameToAliasMapping'][$originalClassName] is iterable.

**Comment by helhum** [comment]
Fixed with #20

**Comment by hdietrich-timespin** [comment]
> Fixed with #20

No is not fixed.

The function TYPO3\ClassAliasLoader::loadOriginalClassAndSetAliases($originalClassName) don't use the fixed function TYPO3\ClassAliasLoader::getOriginalClassName($aliasOrClassName). And so the Issue https://github.com/TYPO3/class-alias-loader/pull/22 and https://github.com/TYPO3/class-alias-loader/issues/21 is not solved!

**Comment by helhum** [comment]
This can not happen any more, latest with 1.2.2 release see #38

if `$this->aliasMap['classNameToAliasMapping'][$originalClassName]` is not iterable, then the original claas loader will be triggered
